### PR TITLE
implement dying

### PR DESCRIPTION
**Pull request by grezisek1**

### CODE REVIEW

**Review by NerdbordMentor — CHANGES_REQUESTED** [review]
### Code Review

#### Task Requirements
1. **Set `dead` state when health is equal or below 0**
2. **Disable action buttons and replace them with a Restart button**

#### Code Changes Review

1. **Set `dead` state when health is equal or below 0**

   - The code introduces a new state `dead` in the `SPRITES` object:
     ```js
     dead: ["url('./sprites/dead.svg')"],
     ```
   - A constant `#GENERAL_STATE_GAMEOVER` is added to represent the `dead` state:
     ```js
     static #GENERAL_STATE_GAMEOVER = "dead";
     ```
   - The `#applyGeneralStateUpdateLogic` method is updated to set the `dead` state when health is 0:
     ```js
     #applyGeneralStateUpdateLogic() {
       if (parseInt(state.elements.health.value) == 0) {
         this.#setGeneralState("dead");
         return;
       }
       // other conditions...
     }
     ```

   This change correctly sets the `dead` state when health is equal to 0, fulfilling the first requirement.

2. **Disable action buttons and replace them with a Restart button**

   - The `#onStateUpdate` method is updated to enable the restart button when the general state is `dead`:
     ```js
     #onStateUpdate = (e) => {
       if (e.detail.general) {
         this.#setSprite(e.detail.general);
         if (e.detail.general == Game.#GENERAL_STATE_GAMEOVER) {
           this.state.elements.restart.disabled = false;
         }
         return;
       }
       // other conditions...
     }
     ```
   - The `#restart` method is updated to disable the restart button and clear/restart the game interval:
     ```js
     this.state.elements.restart.disabled = true;
     
     clearInterval(this.#gameInterval);
     this.#gameInterval = setInterval(this.#gameTick, Game.TICK_DELTA_TIME);
     ```

   However, there is no explicit code to disable the action buttons when the game is over. This needs to be addressed to fully meet the second requirement.

#### Suggested Improvement

To fully meet the second requirement, you should add logic to disable all action buttons when the game state is `dead`. For example:

```js
#onStateUpdate = (e) => {
  if (e.detail.general) {
    this.#setSprite(e.detail.general);
    if (e.detail.general == Game.#GENERAL_STATE_GAMEOVER) {
      this.state.elements.restart.disabled = false;
      // Disable all action buttons
      const actionButtons = this.state.querySelectorAll('.action-button');
      actionButtons.forEach(button => button.disabled = true);
    }
    return;
  }
  // other conditions...
}
```

### Summary

- **Requirement 1**: Met. The code correctly sets the `dead` state when health is 0.
- **Requirement 2**: Partially met. The restart button is enabled, but action buttons are not disabled.

To fully meet the requirements, ensure that all action buttons are disabled when the game state is `dead`.

**Comment by grezisek1** [comment]
action buttons are hidden in line 112 of the `styles.css` file. i will consider adding keyboard support later

**Review by NerdbordMentor — CHANGES_REQUESTED** [review]
### Code Review

Based on the task requirements, the following points need to be validated:

1. **Set `dead` state when health is equal or below 0.**
2. **Disable action buttons and replace them with a Restart button when in the `dead` state.**

#### Review of Code Changes

1. **Setting `dead` state when health is equal or below 0:**

   ```diff
   +    dead: ["url('./sprites/dead.svg')"],
   +  static #GENERAL_STATE_GAMEOVER = "dead";
   ```

   The `dead` state has been added to the sprites and a constant for the game-over state has been defined.

   ```diff
   +    if (parseInt(state.elements.health.value) == 0) {
   +      this.#setGeneralState("dead");
   +      return;
   +    }
   ```

   The code correctly checks if the health value is `0` and sets the general state to `dead`.

2. **Disabling action buttons and replacing them with a Restart button:**

   ```diff
   +      if (e.detail.general == Game.#GENERAL_STATE_GAMEOVER) {
   +        this.state.elements.restart.disabled = false;
   +      }
   ```

   This part of the code enables the restart button when the general state is `dead`.

   ```diff
   +    clearInterval(this.#gameInterval);
   +    this.#gameInterval = setInterval(this.#gameTick, Game.TICK_DELTA_TIME);
   ```

   The game interval is cleared and reset during the restart, ensuring that the game logic is properly reset.

#### Missing Implementation

- **Disabling Action Buttons:**
  
  The requirement specifies that action buttons should be disabled when the Tamagotchi is dead. However, there is no code in the provided changes that disables these action buttons. You need to add logic to disable all action buttons when the `dead` state is set.

  Example:
  ```javascript
  #applyGeneralStateUpdateLogic() {
    if (parseInt(state.elements.health.value) == 0) {
      this.#setGeneralState("dead");
      this.#disableActionButtons();
      return;
    }
    // existing logic...
  }

  #disableActionButtons() {
    const actionButtons = this.state.querySelectorAll('.action-button');
    actionButtons.forEach(button => button.disabled = true);
  }
  ```

### Summary

- **Setting `dead` state:** Implemented correctly.
- **Enabling Restart button:** Implemented correctly.
- **Disabling action buttons:** Missing implementation.

To fully meet the task requirements, you need to add logic to disable all action buttons when the Tamagotchi's health is `0` or below.

**Review by NerdbordMentor — APPROVED** [review]
Force approved. Hope you're not cheating!

**Pull request merged**
